name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: Swatinem/rust-cache@v2
      - run: mise run lint
      - run: mise run test
      - run: mise run release
